from flask import Flask, render_template, request, redirect, url_for, session, flash, jsonify
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail, Message
from datetime import date, timedelta
import json
import os
import io
from fpdf import FPDF  # Pure Python PDF generation - works perfectly on Python 3.14
from werkzeug.utils import secure_filename

app = Flask(__name__)

app.secret_key = 'reginald_sherq_secret_key_2026'

# --- EMAIL CONFIGURATION ---
app.config['MAIL_SERVER'] = 'smtp.gmail.com'
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_USERNAME'] = 'olwethuthandeka7@gmail.com'
app.config['MAIL_PASSWORD'] = 'vkjtvipazvubycsl'  # Your verified Google App Password
mail = Mail(app)

# Database Configuration
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql+psycopg2://postgres:Simangele21%40@localhost:5433/SHERQ'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

UPLOAD_FOLDER = 'static/uploads'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

db = SQLAlchemy(app)

# --- DATABASE MODELS ---
class Extinguisher(db.Model):
    __tablename__ = 'extinguishers'
    id_extinguishers = db.Column(db.Integer, primary_key=True)
    qr_code_id = db.Column(db.String(50))
    extinguisher_type = db.Column(db.String(100))
    unit_weight = db.Column(db.String(20))
    authorized_location = db.Column(db.String(255))
    status = db.Column(db.String(50))
    last_comment = db.Column(db.Text, name='last_ispection_date')

class HoseReel(db.Model):
    __tablename__ = 'hose_reels'
    id = db.Column(db.Integer, primary_key=True)
    qr_code_id = db.Column(db.String(50))
    authorized_location = db.Column(db.String(255))
    status = db.Column(db.String(50))
    unit_weight = db.Column(db.String(20))

class Hydrant(db.Model):
    __tablename__ = 'hydrants'
    id = db.Column(db.Integer, primary_key=True)
    qr_code_id = db.Column(db.String(50))
    authorized_location = db.Column(db.String(255))
    status = db.Column(db.String(50))
    unit_weight = db.Column(db.String(20))

class InspectionReport(db.Model):
    __tablename__ = 'inspection_reports'
    id = db.Column(db.Integer, primary_key=True)
    qr_code_id = db.Column(db.String(50))
    inspector_name = db.Column(db.String(100))
    inspection_date = db.Column(db.Date)
    due_date = db.Column(db.Date)
    category = db.Column(db.String(50))
    responses = db.Column(db.Text)
    report_status = db.Column(db.String(50), default='Created')
    deleted_at = db.Column(db.Date, nullable=True)

# --- NEW: EMPLOYEE & USER MANAGEMENT SCHEMA ---
class Employee(db.Model):
    __tablename__ = 'employees'
    id = db.Column(db.Integer, primary_key=True)
    employee_number = db.Column(db.String(50), unique=True, nullable=False)
    full_name = db.Column(db.String(150), nullable=False)
    email = db.Column(db.String(100))
    role = db.Column(db.String(50), default='Inspector')

class User(db.Model):
    __tablename__ = 'users'
    user_id = db.Column(db.Integer, primary_key=True)
    employee_number = db.Column(db.String(50), db.ForeignKey('employees.employee_number'), nullable=False)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)

# --- HELPER FUNCTIONS ---
def get_unit_and_category(qr_id):
    unit = Extinguisher.query.filter_by(qr_code_id=qr_id).first()
    category = 'Fire Extinguisher'
    if not unit:
        unit = HoseReel.query.filter_by(qr_code_id=qr_id).first()
        category = 'Fire Hose Reel'
    if not unit:
        unit = Hydrant.query.filter_by(qr_code_id=qr_id).first()
        category = 'Fire Hydrant'
    return unit, category

# --- CUSTOM FPDF DESIGN CLASS ---
class SHERQ_PDF(FPDF):
    def header(self):
        self.set_fill_color(26, 54, 93)  # Navy blue background
        self.rect(0, 0, 210, 38, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 18)
        self.cell(0, 12, "OFFICIAL INSPECTION RECORD", align="C", ln=True)
        self.set_font("Helvetica", "", 10)
        self.cell(0, 4, "Reginald SHERQ Management System", align="C", ln=True)
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(160, 174, 192)
        self.cell(0, 10, "Automated operational report generated by Reginald SHERQ Dashboard System.", align="C")

# --- INJECTED GLOBAL FRONTEND CSS OVERRIDES ---
@app.context_processor
def inject_custom_css():
    css_fix = """
    <style>
    .modal-content, [id*="edit"], [class*="edit"], form[action*="edit"], form[action*="update"] {
        background-color: #ffffff !important;
        opacity: 1 !important;
    }
    .modal, .modal-dialog, [id*="edit"] {
        z-index: 99999 !important;
        position: relative;
    }
    input, select, textarea {
        pointer-events: auto !important;
        position: relative !important;
        z-index: 999999 !important;
        background-color: #ffffff !important;
        color: #000000 !important;
    }
    </style>
    """
    return dict(custom_css_override=css_fix)

# --- EMAIL ROUTE WITH PDF ATTACHMENT ---
@app.route('/send_report_email/<int:report_id>', methods=['POST'])
def send_report_email(report_id):
    if not session.get('admin_logged_in'):
        return jsonify({"success": False, "error": "Unauthorized"}), 403
    data = request.get_json()
    recipient = data.get('email')
    if not recipient:
        return jsonify({"success": False, "error": "No recipient email provided."}), 400

    report = InspectionReport.query.get_or_404(report_id)
    unit, category = get_unit_and_category(report.qr_code_id)
    responses = json.loads(report.responses)
    current_questions = {
        'q1': 'Is it mounted correctly?', 'q2': 'Is it visible?', 'q3': 'No physical damage?',
        'q4': 'Instructions legible?', 'q5': 'Safety pin in place?', 'q6': 'Tamper seal intact?',
        'q7': 'Pressure gauge green?', 'q8': 'Full weight?', 'q9': 'Hose clear?',
        'q10': 'Service tag present?', 'q11': 'Serviced in 12 months?', 'q12': 'Correct risk type?',
        'h1': 'Hose accessible?', 'h2': 'Signage visible?', 'h3': 'Hose good condition?',
        'h4': 'Drum secure?', 'h5': 'Valve opens?', 'h6': 'Water pressure OK?',
        'h7': 'Unwinds smoothly?', 'h8': 'Nozzle works?', 'h9': 'Tags updated?', 'h10': 'Tested recently?',
        'y1': 'Hydrant accessible?', 'y2': 'Clear signage?', 'y3': '1m clearance?', 'y4': 'No damage?',
        'y5': 'Caps present?', 'y6': 'Threads clean?', 'y7': 'Properly painted?', 'y8': 'Valve smooth?',
        'y9': 'No leakage?', 'y10': 'Stems good?', 'y11': 'Reliable supply?', 'y12': 'Pressure adequate?',
        'y13': 'Flow test done?', 'y14': 'Couplings compatible?', 'y15': 'Gaskets good?', 'y16': 'Leak-free use?',
        'y17': 'Drains properly?', 'y18': 'No pooling?', 'y19': 'Compliant?', 'y20': 'Inspected recently?',
        'y21': 'Records updated?', 'y22': 'Maintenance records available?', 'y23': 'Serviced regularly?', 'y24': 'Repairs required?'
    }
    
    if report.category and "Recovery" in report.category:
        for key in responses.keys():
            if key not in current_questions:
                current_questions[key] = key

    try:
        pdf = SHERQ_PDF()
        pdf.add_page()
        pdf.set_margins(15, 20, 15)
        pdf.set_fill_color(247, 250, 252)
        pdf.set_text_color(45, 55, 72)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(90, 8, f" Asset Reference: {report.qr_code_id}", border=1, fill=True)
        pdf.cell(90, 8, f" Asset Category: {category}", border=1, fill=True, ln=True)
        location_txt = unit.authorized_location if unit else 'N/A'
        inspector_txt = report.inspector_name if report.inspector_name else 'N/A'
        pdf.cell(90, 8, f" Assigned Location: {location_txt}", border=1, fill=True)
        pdf.cell(90, 8, f" Inspector: {inspector_txt}", border=1, fill=True, ln=True)
        pdf.cell(90, 8, f" Inspection Date: {report.inspection_date}", border=1, fill=True)
        pdf.cell(90, 8, f" Operational Status: {report.report_status}", border=1, fill=True, ln=True)
        pdf.ln(10)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(26, 54, 93)
        pdf.cell(140, 10, "Checklist Audit Question", border="B")
        pdf.cell(40, 10, "Response Metric", border="B", align="C", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(74, 85, 104)
        for key, val in responses.items():
            question_text = current_questions.get(key, key)
            status_val = str(val).upper()
            pdf.cell(140, 9, question_text, border="B")
            if status_val == 'YES':
                pdf.set_text_color(40, 167, 69)
            elif status_val == 'NO':
                pdf.set_text_color(220, 53, 69)
            else:
                pdf.set_text_color(108, 117, 125)
            pdf.cell(40, 9, status_val, border="B", align="C", ln=True)
            pdf.set_text_color(74, 85, 104)
        pdf_bytes = pdf.output()

        subject_heading = f"Reginald SHERQ | Download Official Inspection Report for {report.qr_code_id}"
        msg = Message(subject=subject_heading, sender=app.config['MAIL_USERNAME'], recipients=[recipient])
        msg.body = f"Good day,\n\nPlease find attached the official completed inspection report PDF file for {category}.\n\nBest Regards,\nReginald SHERQ Management System"
        msg.attach(filename=f"Inspection_Report_{report.qr_code_id}.pdf", content_type="application/pdf", data=pdf_bytes)
        mail.send(msg)
        return jsonify({"success": True})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route('/view_report/<int:report_id>')
def view_report(report_id):
    report = InspectionReport.query.get_or_404(report_id)
    unit, category = get_unit_and_category(report.qr_code_id)
    responses = json.loads(report.responses)
    current_questions = {
        'q1': 'Is it mounted correctly?', 'q2': 'Is it visible?', 'q3': 'No physical damage?',
        'q4': 'Instructions legible?', 'q5': 'Safety pin in place?', 'q6': 'Tamper seal intact?',
        'q7': 'Pressure gauge green?', 'w8': 'Full weight?', 'q9': 'Hose clear?',
        'q10': 'Service tag present?', 'q11': 'Serviced in 12 months?', 'q12': 'Correct risk type?',
        'h1': 'Hose accessible?', 'h2': 'Signage visible?', 'h3': 'Hose good condition?',
        'h4': 'Drum secure?', 'h5': 'Valve opens?', 'h6': 'Water pressure OK?',
        'h7': 'Unwinds smoothly?', 'h8': 'Nozzle works?', 'h9': 'Tags updated?', 'h10': 'Tested recently?',
        'y1': 'Hydrant accessible?', 'y2': 'Clear signage?', 'y3': '1m clearance?', 'y4': 'No damage?',
        'y5': 'Caps present?', 'y6': 'Threads clean?', 'y7': 'Properly painted?', 'y8': 'Valve smooth?',
        'y9': 'No leakage?', 'y10': 'Stems good?', 'y11': 'Reliable supply?', 'y12': 'Pressure adequate?',
        'y13': 'Flow test done?', 'y14': 'Couplings compatible?', 'y15': 'Gaskets good?', 'y16': 'Leak-free use?',
        'y17': 'Drains properly?', 'y18': 'No pooling?', 'y19': 'Compliant?', 'y20': 'Inspected recently?',
        'y21': 'Records updated?', 'y22': 'Maintenance records available?', 'y23': 'Serviced regularly?', 'y24': 'Repairs required?'
    }

    if report.category and "Recovery" in report.category:
        for key in responses.keys():
            if key not in current_questions:
                current_questions[key] = key

    return render_template('view_report.html', report=report, unit=unit, responses=responses, current_questions=current_questions)

@app.route('/admin/alerts')
def admin_alerts():
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    raw_alerts = InspectionReport.query.filter(InspectionReport.category.like('%Recovery%')).order_by(InspectionReport.inspection_date.desc()).all()
    misplaced_alerts = []
    for alert in raw_alerts:
        try:
            res_data = json.loads(alert.responses)
            if res_data.get("Is Unit Returned To Authorized Position?") == "NO" or alert.report_status == 'In Progress':
                asset_obj, cat = get_unit_and_category(alert.qr_code_id)
                loc = asset_obj.authorized_location if asset_obj else "System Track Misplaced"
                misplaced_alerts.append({
                    'id': alert.id,
                    'report_status': alert.report_status,
                    'qr_code_id': alert.qr_code_id, 'authorized_location': loc, 'inspector_name': alert.inspector_name,
                    'comments': res_data.get("Operational Comments / Reason for Move", "No operational obstacle reported."),
                    'responsible': res_data.get("Reported Escalation Manager", "Management Response Team"),
                    'due_date': res_data.get("Expected Target Resolution Date", "Immediate Attention Required")
                })
        except Exception:
            continue
    return render_template('alerts.html', misplaced_alerts=misplaced_alerts)

@app.route('/admin/resolve_alert/<int:report_id>')
def resolve_alert(report_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    report = InspectionReport.query.get_or_404(report_id)
    unit, category = get_unit_and_category(report.qr_code_id)
    report.report_status = 'Completed'
    if unit:
        unit.status = 'In Position'
    db.session.commit()
    flash(f"Asset {report.qr_code_id} has been resolved.", "success")
    return redirect(url_for('admin_alerts'))

@app.route('/admin/dashboard')
def admin_dashboard():
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    all_reports = InspectionReport.query.order_by(InspectionReport.inspection_date.desc()).limit(10).all()
    total_inspections = InspectionReport.query.count()
    completed = InspectionReport.query.filter_by(report_status='Completed').count()
    in_progress = InspectionReport.query.filter_by(report_status='In Progress').count()
    created = InspectionReport.query.filter_by(report_status='Created').count()
    raw_alerts = InspectionReport.query.filter(InspectionReport.category.like('%Recovery%')).order_by(InspectionReport.inspection_date.desc()).all()
    misplaced_alerts = []
    for alert in raw_alerts:
        try:
            res_data = json.loads(alert.responses)
            if res_data.get("Is Unit Returned To Authorized Position?") == "NO":
                asset_obj, cat = get_unit_and_category(alert.qr_code_id)
                loc = asset_obj.authorized_location if asset_obj else "System Track Misplaced"
                misplaced_alerts.append({
                    'qr_code_id': alert.qr_code_id, 'authorized_location': loc, 'inspector_name': alert.inspector_name,
                    'comments': res_data.get("Operational Comments / Reason for Move", "No operational obstacle reported."),
                    'responsible': res_data.get("Reported Escalation Manager", "Management Response Team"),
                    'due_date': res_data.get("Expected Target Resolution Date", "Immediate Attention Required")
                })
        except Exception:
            continue
    return render_template('admin_dashboard.html', reports=all_reports, total=total_inspections, completed_count=completed, in_progress_count=in_progress, created_count=created, misplaced_alerts=misplaced_alerts)

@app.route('/admin/register')
def register():
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    raw_extinguishers = Extinguisher.query.all()
    raw_hoses = HoseReel.query.all()
    raw_hydrants = Hydrant.query.all()
    extinguishers = [{'qr_code_id': item.qr_code_id, 'type': item.extinguisher_type, 'unit_weight': item.unit_weight, 'location': item.authorized_location, 'status': item.status or 'In Position'} for item in raw_extinguishers]
    hoses = [{'qr_code_id': item.qr_code_id, 'unit_weight': item.unit_weight or 'Standard 30m', 'location': item.authorized_location, 'status': item.status or 'In Position'} for item in raw_hoses]
    hydrants = [{'qr_code_id': item.qr_code_id, 'unit_weight': item.unit_weight or 'Standard Flow', 'location': item.authorized_location, 'status': item.status or 'In Position'} for item in raw_hydrants]
    return render_template('register.html', extinguishers=extinguishers, hoses=hoses, hydrants=hydrants)

@app.route('/admin/add_asset/<category>', methods=['GET', 'POST'])
def add_asset(category):
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    if category in ['extinguisher', 'extinguishers', 'Fire Extinguisher']:
        next_num = Extinguisher.query.count() + 1
        generated_id = f"EQ-{next_num:03d}"
    elif category in ['hose_reel', 'hose', 'Fire Hose Reel']:
        next_num = HoseReel.query.count() + 1
        generated_id = f"HSR-{next_num:03d}"
    else:
        next_num = Hydrant.query.count() + 1
        generated_id = f"HYD-{next_num:03d}"
    if request.method == 'POST':
        form_location = request.form.get('location')
        form_weight = request.form.get('weight') or request.form.get('unit_weight')
        if category in ['extinguisher', 'extinguishers', 'Fire Extinguisher']:
            new_asset = Extinguisher(qr_code_id=generated_id, extinguisher_type=request.form.get('type', 'ABC Powder'), unit_weight=form_weight, authorized_location=form_location, status='In Position')
        elif category in ['hose_reel', 'hose', 'Fire Hose Reel']:
            new_asset = HoseReel(qr_code_id=generated_id, unit_weight=form_weight or 'Standard 30m', authorized_location=form_location, status='In Position')
        else:
            new_asset = Hydrant(qr_code_id=generated_id, unit_weight=form_weight or 'Standard Flow', authorized_location=form_location, status='In Position')
        db.session.add(new_asset)
        db.session.commit()
        flash(f"Asset {generated_id} added successfully!")
        return redirect(url_for('register'))
    return render_template('add_asset.html', category=category, next_id=generated_id)

@app.route('/admin/view_history/<qr_id>')
def view_history(qr_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    unit, category = get_unit_and_category(qr_id)
    historical_reports = InspectionReport.query.filter_by(qr_code_id=qr_id).order_by(InspectionReport.inspection_date.desc()).all()
    return render_template('history.html', qr_code_id=qr_id, unit=unit, category=category, reports=historical_reports)

@app.route('/admin/edit_asset/<category>/<qr_id>', methods=['GET', 'POST'])
def edit_asset(category, qr_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    unit, assigned_category = get_unit_and_category(qr_id)
    if request.method == 'POST':
        if unit:
            unit.authorized_location = request.form.get('location') or request.form.get('authorized_location')
            unit.unit_weight = request.form.get('unit_weight') or request.form.get('weight')
            if hasattr(unit, 'extinguisher_type'):
                unit.extinguisher_type = request.form.get('type') or request.form.get('extinguisher_type')
            db.session.commit()
            flash(f"Asset {qr_id} updated successfully!")
            return redirect(url_for('register'))
    return render_template('edit_asset.html', category=category, qr_id=qr_id, item=unit)

@app.route('/admin/toggle_inactive/<category>/<qr_id>')
def toggle_inactive(category, qr_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    unit, assigned_category = get_unit_and_category(qr_id)
    if unit:
        unit.status = 'Inactive'
        db.session.commit()
        flash(f"Asset {qr_id} marked as inactive.")
    return redirect(url_for('register'))

@app.route('/admin/inspection_register')
def inspection_register():
    if not session.get('admin_logged_in'): 
        return redirect(url_for('login'))
    
    # We filter by deleted_at is None so only active items are shown
    all_inspections = InspectionReport.query.filter(InspectionReport.deleted_at.is_(None)).order_by(InspectionReport.inspection_date.desc()).all()
    
    # We also update stats to count only non-deleted items
    stats = {
        'total': InspectionReport.query.filter(InspectionReport.deleted_at.is_(None)).count(), 
        'completed': InspectionReport.query.filter_by(report_status='Completed', deleted_at=None).count(),
        'in_progress': InspectionReport.query.filter_by(report_status='In Progress', deleted_at=None).count(), 
        'created': InspectionReport.query.filter_by(report_status='Created', deleted_at=None).count()
    }
    return render_template('inspection_register.html', inspections=all_inspections, stats=stats)

@app.route('/admin/employees', methods=['GET', 'POST'])
def employee_management():
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    if request.method == 'POST':
        emp_num = request.form.get('employee_number', '').strip()
        name = request.form.get('full_name', '').strip()
        email = request.form.get('email', '').strip()
        role = request.form.get('role', 'Inspector')
        if Employee.query.filter_by(employee_number=emp_num).first():
            flash(f"Employee ID {emp_num} is already registered.", "danger")
        else:
            db.session.add(Employee(employee_number=emp_num, full_name=name, email=email, role=role))
            db.session.commit()
            flash("Employee registered successfully!", "success")
    return render_template('employee_management.html', employees=Employee.query.order_by(Employee.employee_number.asc()).all())

@app.route('/admin/employees/update/<int:id>', methods=['POST'])
def update_employee(id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    emp = Employee.query.get_or_404(id)
    emp.full_name = request.form.get('full_name', '').strip()
    emp.email = request.form.get('email', '').strip()
    emp.role = request.form.get('role')
    db.session.commit()
    flash("Employee updated.", "success")
    return redirect(url_for('employee_management'))

@app.route('/admin/employees/delete/<int:id>')
def delete_employee(id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    db.session.delete(Employee.query.get_or_404(id))
    db.session.commit()
    flash("Employee removed.", "warning")
    return redirect(url_for('employee_management'))

@app.route('/api/validate_inspector', methods=['POST'])
def validate_inspector():
    emp = Employee.query.filter_by(employee_number=(request.get_json() or {}).get('employee_number', '').strip()).first()
    return jsonify({"valid": True, "inspector_name": emp.full_name}) if emp else jsonify({"valid": False, "message": "Access Denied"}), 401 if not emp else 200

@app.route('/delete_inspection/<int:report_id>', methods=['POST'])
def delete_inspection(report_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('login'))
    report = InspectionReport.query.get_or_404(report_id)
    report.deleted_at = date.today() # Mark date for 30-day countdown
    db.session.commit()
    flash("Report moved to Recycle Bin.", "warning")
    return redirect(url_for('inspection_register'))

@app.route('/login', methods=['GET', 'POST'])
def login():
    # Capture the 'next' URL parameter if it exists (e.g., /questionnaire/EQ-001)
    next_url = request.args.get('next')
    
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()
        
        if user and user.password_hash == password:
            session['admin_logged_in'] = True
            session['username'] = user.username
            
            # Redirect to the intended page (next_url) or fallback to dashboard
            return redirect(next_url or url_for('admin_dashboard'))
        else:
            flash("Invalid username or password.", "danger")
            
    return render_template('log_html.html')

app.add_url_rule('/admin/employees', endpoint='employee_management', view_func=employee_management)
app.add_url_rule('/admin/register', endpoint='register', view_func=register)
app.add_url_rule('/admin/inspection_register', endpoint='inspection_register', view_func=inspection_register)

@app.route('/logout')
def logout():
    session.pop('admin_logged_in', None)
    return redirect(url_for('login'))

@app.route('/scan/<string:qr_code_id>')
def scan_asset(qr_code_id):
    unit, category = get_unit_and_category(qr_code_id)
    return render_template('details.html', unit=unit, category=category) if unit else ("Not Found", 404)

@app.route('/details/<string:qr_code_id>')
def details(qr_code_id):
    unit, category = get_unit_and_category(qr_code_id)
    return render_template('details.html', unit=unit, category=category) if unit else ("Not Found", 404)

@app.route('/questionnaire/<string:qr_code_id>')
def load_questionnaire(qr_code_id):
    unit, category = get_unit_and_category(qr_code_id)
    return render_template('questionnaire.html', unit=unit, category=category, today_date=date.today().isoformat(), employees=Employee.query.order_by(Employee.full_name.asc()).all()) if unit else ("Not Found", 404)

@app.route('/recovery/<string:qr_code_id>')
def load_recovery(qr_code_id):
    unit, category = get_unit_and_category(qr_code_id)
    return render_template('recovery.html', unit=unit, category=category, employees=Employee.query.order_by(Employee.full_name.asc()).all()) if unit else ("Not Found", 404)

@app.route('/submit_recovery/<string:qr_code_id>', methods=['POST'])
def submit_recovery(qr_code_id):
    unit, category = get_unit_and_category(qr_code_id)
    if not unit: return "Not Found", 404
    clean_resp = 'yes' if 'yes' in request.form.get('will_recover', '').lower() else 'no'
    res_dict = {"Is Unit Returned To Authorized Position?": clean_resp.upper(), "Operational Comments / Reason for Move": request.form.get('comments', 'No comments.')}
    if clean_resp == 'no':
        res_dict.update({"Reported Escalation Manager": request.form.get('responsible', 'N/A'), "Expected Target Resolution Date": request.form.get('due_date')})
    new_report = InspectionReport(qr_code_id=qr_code_id, inspector_name=request.form.get('inspector_name'), inspection_date=date.today(), category=f"Recovery Checklist: {category}", responses=json.dumps(res_dict), report_status="In Progress" if clean_resp == 'no' else "Completed")
    db.session.add(new_report)
    if unit: unit.status = 'In Position' if clean_resp == 'yes' else 'Displaced'
    db.session.commit()
    return redirect(url_for('view_report', report_id=new_report.id))

@app.route('/submit_inspection/<string:qr_code_id>', methods=['POST'])
def submit_inspection(qr_code_id):
    unit, category = get_unit_and_category(qr_code_id)
    if not unit: return "Not Found", 404
    resp = {k: v for k, v in request.form.items() if k not in ['inspector_name', 'inspection_date'] and not k.endswith('_comment')}
    new_report = InspectionReport(qr_code_id=qr_code_id, inspector_name=request.form.get('inspector_name'), inspection_date=date.fromisoformat(request.form.get('inspection_date', str(date.today()))), category=category, responses=json.dumps(resp), report_status='Completed')
    db.session.add(new_report)
    unit.status = 'In Position'
    db.session.commit()
    return render_template('thank_you.html', unit=unit, category=category, unit_id=qr_code_id, inspector_name=request.form.get('inspector_name'), report_id=new_report.id)

@app.route('/admin/recycle_bin')
def recycle_bin():
    if not session.get('admin_logged_in'): 
        return redirect(url_for('login'))
    
    # 1. Cleanup: Permanently delete anything > 30 days old
    threshold = date.today() - timedelta(days=30)
    old_items = InspectionReport.query.filter(InspectionReport.deleted_at < threshold).all()
    for item in old_items:
        db.session.delete(item)
    db.session.commit()

    # 2. Display items that are in the bin
    trashed = InspectionReport.query.filter(InspectionReport.deleted_at.isnot(None)).all()
    return render_template('recycle_bin.html', trashed=trashed)

@app.route('/restore_item/<int:report_id>', methods=['POST'])
def restore_item(report_id):
    if not session.get('admin_logged_in'): 
        return redirect(url_for('login'))
    report = InspectionReport.query.get_or_404(report_id)
    report.deleted_at = None 
    db.session.commit()
    flash("Report restored successfully!", "success")
    return redirect(url_for('recycle_bin'))

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(debug=True)
       
        

    
        

    
    
